(()=>{'use strict';
// Only point fields are drawn. No mesh, surface, solid primitive or model loader.
const $=id=>document.getElementById(id),V=(x=0,y=0,z=0)=>new THREE.Vector3(x,y,z),GOLD=0xeac38b,BLUE=0xaecbd0;
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));let seed=728;function rand(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;}
let renderer;try{renderer=new THREE.WebGLRenderer({canvas:$('world'),antialias:false});}catch{$('error').style.display='block';$('error').textContent='请用支持 WebGL 的电脑浏览器打开。';return;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor(0x080909);const scene=new THREE.Scene(),world=new THREE.Group();scene.add(world);const camera=new THREE.PerspectiveCamera(47,innerWidth/innerHeight,.1,180);camera.position.set(0,2,17);let look=V(0,1.5,0);
let chapter=-1,mode='intro',paused=false,muted=false,busy=false,time=0,last=0,cam=null,anim=[],actors=[],hotspots=[],drag=null,hold=null;let st={chapter:0,ration:[0,0],path:'',boundary:'',decision:''};try{let saved=JSON.parse(localStorage.getItem('river-particle-v4'));if(saved&&saved.chapter>0){st=saved;$('continue').style.display='block';}}catch{}
const vert=`uniform float uTime;uniform float uSize;uniform float uScatter;attribute float aSeed;varying float vSeed;varying float vZ;void main(){vSeed=aSeed;vec3 p=position;float a=aSeed*112.;p+=vec3(sin(a*1.3+uTime*.27),cos(a*.7+uTime*.19),sin(a*1.9+uTime*.17))*.024;p+=vec3(sin(a)*7.,cos(a*1.7)*5.,sin(a*.73)*6.)*uScatter;vec4 mv=modelViewMatrix*vec4(p,1.);vZ=-mv.z;gl_Position=projectionMatrix*mv;gl_PointSize=clamp(uSize*610./max(2.,-mv.z),.8,3.6);}`;
const frag=`uniform vec3 uColor;uniform float uTime;uniform float uOpacity;varying float vSeed;varying float vZ;void main(){float d=length(gl_PointCoord-.5);if(d>.5)discard;float a=pow(1.-2.*d,1.3)*(.65+.35*sin(vSeed*41.+uTime*.45));gl_FragColor=vec4(uColor*(.58+vSeed*.5),a*uOpacity*.85*exp(-vZ*.004));}`;
function points(coords,color=GOLD,size=.06,parent=world){let geo=new THREE.BufferGeometry(),seeds=[];for(let i=0;i<coords.length/3;i++)seeds.push(rand());geo.setAttribute('position',new THREE.Float32BufferAttribute(coords,3));geo.setAttribute('aSeed',new THREE.Float32BufferAttribute(seeds,1));let mat=new THREE.ShaderMaterial({vertexShader:vert,fragmentShader:frag,uniforms:{uTime:{value:0},uSize:{value:size},uScatter:{value:0},uColor:{value:new THREE.Color(color)},uOpacity:{value:1}},transparent:true,depthWrite:false,blending:THREE.AdditiveBlending});let p=new THREE.Points(geo,mat);p.userData={alpha:.65,scatter:0};parent.add(p);actors.push(p);return p;}
function mask(type,q){q.fillStyle='#fff';q.strokeStyle='#fff';q.lineWidth=10;q.lineCap='round';q.lineJoin='round';q.beginPath();
if(type==='person'){q.ellipse(256,95,39,50,0,0,Math.PI*2);q.fill();q.beginPath();q.moveTo(240,143);q.bezierCurveTo(185,146,162,181,170,258);q.lineTo(152,325);q.lineTo(180,332);q.lineTo(197,265);q.lineTo(198,363);q.lineTo(182,481);q.lineTo(220,481);q.lineTo(252,375);q.lineTo(282,481);q.lineTo(319,481);q.lineTo(303,363);q.lineTo(306,252);q.lineTo(332,325);q.lineTo(355,315);q.bezierCurveTo(329,189,331,148,273,143);q.closePath();q.fill();}
if(type==='hand'){q.moveTo(185,490);q.lineTo(180,343);q.bezierCurveTo(119,284,92,235,128,230);q.bezierCurveTo(151,226,171,270,191,279);q.lineTo(184,100);q.bezierCurveTo(182,68,204,63,211,99);q.lineTo(232,233);q.lineTo(226,65);q.bezierCurveTo(225,30,250,28,255,65);q.lineTo(270,224);q.lineTo(278,72);q.bezierCurveTo(280,40,302,45,301,79);q.lineTo(306,245);q.lineTo(322,126);q.bezierCurveTo(328,99,349,104,344,132);q.lineTo(340,328);q.bezierCurveTo(340,356,315,376,303,402);q.lineTo(299,490);q.closePath();q.fill();}
if(type==='ticket'){q.lineWidth=5;q.strokeRect(78,160,356,202);for(let x=82;x<428;x+=18){q.moveTo(x,159);q.lineTo(x,168);q.moveTo(x,361);q.lineTo(x,352);}q.stroke();q.font='72px FilmSong';q.textAlign='center';q.fillText('粮票',256,268);q.font='24px FilmHei';q.fillText('生活示意',256,316);}
if(type==='money'){for(let i=0;i<3;i++){q.beginPath();q.ellipse(250+i*8,310-i*28,82,25,0,0,Math.PI*2);q.stroke();}q.beginPath();q.moveTo(178,300);q.lineTo(178,332);q.moveTo(345,254);q.lineTo(345,313);q.stroke();}
if(type==='sack'){q.moveTo(225,90);q.lineTo(287,90);q.lineTo(280,145);q.bezierCurveTo(399,230,367,430,315,455);q.bezierCurveTo(244,482,148,453,145,369);q.bezierCurveTo(122,225,168,192,231,142);q.closePath();q.fill();}
if(type==='case'){q.lineWidth=5;q.strokeRect(95,165,322,224);q.strokeRect(201,130,111,36);for(let x of [160,352]){q.moveTo(x,171);q.lineTo(x,382);}q.stroke();}
if(type==='train'){q.lineWidth=6;q.moveTo(37,224);q.bezierCurveTo(35,169,61,150,99,150);q.lineTo(472,150);q.lineTo(472,364);q.lineTo(37,364);q.closePath();q.stroke();for(let x=88;x<468;x+=78){q.strokeRect(x,204,55,66);q.beginPath();q.ellipse(x,382,22,22,0,0,Math.PI*2);q.stroke();}}
if(type==='key'){q.lineWidth=15;q.beginPath();q.ellipse(230,141,60,60,0,0,Math.PI*2);q.stroke();q.beginPath();q.moveTo(230,200);q.lineTo(230,430);q.lineTo(309,430);q.moveTo(234,375);q.lineTo(291,375);q.stroke();}
if(type==='door'){q.lineWidth=6;q.strokeRect(122,74,268,414);q.beginPath();q.ellipse(343,293,11,11,0,0,Math.PI*2);q.stroke();}
if(type==='clock'){q.beginPath();q.ellipse(256,256,157,157,0,0,Math.PI*2);q.stroke();q.beginPath();q.moveTo(256,144);q.lineTo(256,256);q.lineTo(325,300);q.stroke();}
if(type==='phone'){q.lineWidth=7;q.strokeRect(160,80,192,353);q.moveTo(217,112);q.lineTo(292,112);q.moveTo(239,397);q.lineTo(273,397);q.stroke();}
if(type==='rotary'){q.lineWidth=7;q.moveTo(86,365);q.lineTo(120,225);q.lineTo(396,225);q.lineTo(432,365);q.closePath();q.stroke();q.beginPath();q.ellipse(256,281,63,38,0,0,Math.PI*2);q.stroke();q.beginPath();q.moveTo(111,181);q.bezierCurveTo(157,111,346,111,402,184);q.moveTo(127,194);q.bezierCurveTo(168,164,338,164,388,194);q.stroke();}
if(type==='bowl'){q.moveTo(83,232);q.bezierCurveTo(110,401,399,401,430,232);q.stroke();q.beginPath();q.ellipse(256,234,174,37,0,0,Math.PI*2);q.stroke();}
if(type==='grip'){q.moveTo(226,490);q.lineTo(203,364);q.bezierCurveTo(182,337,180,301,204,272);q.bezierCurveTo(223,248,241,245,254,263);q.bezierCurveTo(266,283,256,302,239,304);q.bezierCurveTo(261,321,307,304,306,277);q.lineTo(301,227);q.bezierCurveTo(298,202,322,195,329,220);q.lineTo(343,284);q.bezierCurveTo(350,305,352,340,329,372);q.lineTo(316,490);q.closePath();q.fill();q.beginPath();q.moveTo(265,269);q.bezierCurveTo(237,243,211,216,222,200);q.bezierCurveTo(235,182,260,202,278,220);q.bezierCurveTo(257,183,246,159,263,151);q.bezierCurveTo(282,144,296,171,304,196);q.stroke();}
if(type==='book'){q.lineWidth=6;q.moveTo(255,150);q.bezierCurveTo(205,122,118,134,74,152);q.lineTo(74,397);q.bezierCurveTo(142,374,204,389,255,421);q.bezierCurveTo(305,389,380,374,438,397);q.lineTo(438,152);q.bezierCurveTo(370,133,302,128,255,150);q.lineTo(255,421);q.stroke();for(let j=0;j<5;j++){q.moveTo(110,205+j*32);q.lineTo(210,209+j*32);q.moveTo(296,209+j*32);q.lineTo(398,202+j*32);}q.stroke();}
if(type==='pencil'){q.moveTo(218,441);q.lineTo(228,90);q.lineTo(279,90);q.lineTo(289,441);q.lineTo(253,484);q.closePath();q.stroke();q.moveTo(251,91);q.lineTo(251,434);q.stroke();}
if(type==='lamp'){q.lineWidth=5;q.moveTo(202,100);q.lineTo(310,100);q.lineTo(349,212);q.lineTo(157,212);q.closePath();q.stroke();q.moveTo(254,212);q.lineTo(254,400);q.moveTo(173,410);q.lineTo(334,410);q.stroke();}
if(type==='letter'){q.lineWidth=5;q.strokeRect(62,146,388,238);q.moveTo(62,146);q.lineTo(256,283);q.lineTo(450,146);q.moveTo(62,384);q.lineTo(196,271);q.moveTo(450,384);q.lineTo(312,270);q.stroke();}
if(type==='badge'){q.lineWidth=5;q.strokeRect(130,102,252,353);q.strokeRect(213,79,86,45);q.beginPath();q.ellipse(256,213,42,48,0,0,Math.PI*2);q.stroke();q.moveTo(193,301);q.bezierCurveTo(198,247,312,247,318,301);q.stroke();q.font='38px FilmSong';q.textAlign='center';q.fillText('职工',256,384);}
if(type==='window'){q.lineWidth=5;q.strokeRect(77,53,358,409);q.moveTo(256,53);q.lineTo(256,462);q.moveTo(77,244);q.lineTo(435,244);q.stroke();}
if(type==='rice'){q.lineWidth=5;for(let i=0;i<23;i++){q.beginPath();let x=110+(i*83%295),y=156+(i*61%225);q.ellipse(x,y,8,19,(i%5)*.3,0,Math.PI*2);q.stroke();}}
if(type==='breath'){for(let j=0;j<4;j++){q.beginPath();for(let x=48;x<470;x+=3){let y=190+j*36+Math.sin(x*.012)*35;q.lineTo(x,y);}q.stroke();}}
}
function form(type,x,y,z,w=4,color=GOLD,count=4500){let c=document.createElement('canvas');c.width=c.height=512;let q=c.getContext('2d');mask(type,q);let d=q.getImageData(0,0,512,512).data,coords=[];let tries=0;while(coords.length<count*3&&tries++<count*60){let xx=Math.floor(rand()*512),yy=Math.floor(rand()*512);if(d[(yy*512+xx)*4+3]>90)coords.push((xx-256)/512*w,(256-yy)/512*w,(rand()-.5)*w*.1);}let p=points(coords,color,['sack','money','lamp'].includes(type)?.037:.058);p.position.set(x,y,z);p.userData.type=type;return p;}
function glyph(txt,x,y,z,w=6,color=GOLD){let c=document.createElement('canvas'),q=c.getContext('2d');q.font='120px FilmSong';c.width=Math.ceil(q.measureText(txt).width)+50;c.height=190;q=c.getContext('2d');q.fillStyle='#fff';q.textAlign='center';q.font='120px FilmSong';q.fillText(txt,c.width/2,137);let d=q.getImageData(0,0,c.width,c.height).data,a=[];for(let yy=0;yy<c.height;yy+=2)for(let xx=0;xx<c.width;xx+=2)if(d[(yy*c.width+xx)*4+3]>90)a.push((xx-c.width/2)/c.width*w,(c.height/2-yy)/c.width*w,(rand()-.5)*.16);let p=points(a,color,.055);p.position.set(x,y,z);p.userData.text=txt;return p;}
function after(seconds,fn){let start=time;anim.push({tick(t){if(t-start>=seconds){fn();return true;}return false;}});}
function lightBeam(from,to,width,color=GOLD){let coords=[];for(let i=0;i<18000;i++){let k=rand(),p=from.clone().lerp(to,k),a=rand()*Math.PI*2,r=Math.sqrt(rand())*width*(.12+k);coords.push(p.x+Math.cos(a)*r,p.y+Math.sin(a)*r*.7,p.z+(rand()-.5)*width*.4);}let p=points(coords,color,.04);p.userData.alpha=.085;anim.push({tick(t){p.rotation.z=Math.sin(t*.04)*.012;return false;}});return p;}
function corridor(width=7,length=26,tint=GOLD){let a=[];for(let i=0;i<14000;i++){let z=-length/2+rand()*length;let x=(i%2?-1:1)*(width/2+rand()*.15);a.push(x,rand()*5-1,z);}let p=points(a,tint,.019);p.userData.alpha=.34;let floor=[];for(let i=0;i<9000;i++){let z=rand()*length-length/2;floor.push((rand()-.5)*width,-1.15+rand()*.03,z);}points(floor,tint,.032).userData.alpha=.31;}
function memoryWord(txt,x=0,y=3,z=-7,w=5,color=GOLD){let p=glyph(txt,x,y,z,w,color);reveal(p,2);after(5,()=>tween(p.userData,{scatter:.8,alpha:0},3));return p;}
function morph(a,type,pos,w,d=3,done){let target=form(type,0,0,0,w,a.material.uniforms.uColor.value.getHex(),a.geometry.getAttribute('position').count);world.remove(target);actors=actors.filter(p=>p!==target);let from=a.geometry.getAttribute('position'),to=target.geometry.getAttribute('position'),src=new Float32Array(from.array),start=time,origin=a.position.clone();let shift=pos.clone().sub(origin);anim.push({tick(t){let k=clamp((t-start)/d),e=k*k*(3-2*k);for(let i=0;i<from.count;i++){let j=i%to.count;from.setXYZ(i,src[i*3]*(1-e)+(to.getX(j)+shift.x)*e+Math.sin(k*Math.PI)*Math.sin(i*7)*1.2,src[i*3+1]*(1-e)+(to.getY(j)+shift.y)*e+Math.sin(k*Math.PI)*Math.cos(i*9),src[i*3+2]*(1-e)+(to.getZ(j)+shift.z)*e);}from.needsUpdate=true;if(k>=1){target.geometry.dispose();target.material.dispose();if(done)done();return true;}return false;}});}
function field(){let a=[];for(let i=0;i<10000;i++)a.push((rand()-.5)*110,rand()*38-5,(rand()-.5)*110);let p=points(a,0xa58b64,.024,scene);p.userData.alpha=.42;for(let i=0;i<3;i++){let a=[];for(let j=0;j<4000;j++){let x=(rand()-.5)*65,z=(rand()-.5)*4;a.push(x,-1.2+Math.sin(x*.19)*.16,z-4);}let r=points(a,i===1?BLUE:GOLD,.023,scene);r.userData.alpha=.2;}return p;}let ambient=field();let persistent=actors.slice();
function reveal(actor,seconds=2){actor.userData.alpha=0;actor.userData.scatter=.7;tween(actor.userData,{alpha:.75,scatter:0},seconds);}
function tween(obj,to,duration,done){let from={};Object.keys(to).forEach(k=>from[k]=obj[k]);let start=time;anim.push({tick(t){let k=clamp((t-start)/duration),e=k*k*(3-2*k);Object.keys(to).forEach(j=>obj[j]=from[j]+(to[j]-from[j])*e);if(k>=1){if(done)done();return true;}}});}
function move(a,pos,d=2,done){let from=a.position.clone(),start=time;anim.push({tick(t){let k=clamp((t-start)/d),e=k*k*(3-2*k);a.position.lerpVectors(from,pos,e);a.position.y+=Math.sin(k*Math.PI)*.22;if(k>=1){if(done)done();return true;}}});}
function fly(pos,target,d=3,done){cam={a:camera.position.clone(),b:pos,c:look.clone(),d:target,start:time,dur:d,done};}
function clear(){world.traverse(o=>{if(o.isPoints){o.geometry.dispose();o.material.dispose();}});world.clear();actors=persistent.slice();anim=[];hotspots=[];$('labels').replaceChildren();hold=null;drag=null;cam=null;busy=false;$('choices').replaceChildren();$('sources').style.display='none';}
function say(s){$('subtitle').textContent=s;$('headline').textContent='';}
function hint(s){$('hint').textContent=s;}
function choices(items){$('choices').replaceChildren();items.forEach(([label,fn])=>{let b=document.createElement('button');b.textContent=label;b.onclick=()=>{if(!paused&&!busy){sound('click');fn();}};$('choices').appendChild(b);});}
function hot(actor,label,id,fn,dy=0){let b=document.createElement('button');b.textContent=label;b.dataset.action=id;b.onclick=()=>{if(!paused&&!busy&&!cam)fn();};$('labels').appendChild(b);hotspots.push({actor,b,fn,dy});return b;}
function hideHot(){hotspots.forEach(h=>h.b.style.display='none');}
function save(){st.chapter=chapter;try{localStorage.setItem('river-particle-v4',JSON.stringify(st));}catch{}}
const chapters=[
{year:'1978',age:'3岁',name:'童年',context:'改革开放开始。家里的粮，仍要凭票和钱领。',build:grainScene,score:1,at:6,gain:.24},
{year:'1986',age:'11岁',name:'读书',context:'九年义务教育开始推行。父母把希望放进书包。',build:schoolScene,score:0,at:15,gain:.35},
{year:'1993',age:'18岁',name:'离乡',context:'粮票陆续退出，市场打开。你也走向了远方。',build:trainScene,score:0,at:56,gain:.38},
{year:'1998',age:'23岁',name:'工作',context:'国企改革、下岗分流。有人重新寻找生计。',build:workScene,score:2,at:16,gain:.3},
{year:'2003',age:'28岁',name:'成家',context:'住房改革之后，成家的账开始自己算。',build:keyScene,score:2,at:50,gain:.3},
{year:'2008',age:'33岁',name:'养育',context:'金融危机来了。孩子的明天，仍不能停。',build:familyScene,score:1,at:94,gain:.29},
{year:'2015',age:'40岁',name:'学着跟上',context:'手机支付走进生活。这一次，孩子教你。',build:digitalScene,score:0,at:126,gain:.3},
{year:'2020',age:'45岁',name:'停下的日子',context:'疫情打断日常。距离，突然有了重量。',build:pandemicScene,score:2,at:2,gain:.25},
{year:'2026',age:'父母51岁 · 你23岁',name:'此刻',context:'同一段人生，来到了不同的时代。',build:nowScene,score:1,at:135,gain:.36},
{year:'2026',age:'父母51岁 · 你23岁',name:'电话那端',context:'他们想把过去的答案，交给今天的你。',build:phoneScene,score:0,at:9,gain:.2},
{year:'2026',age:'你的人生',name:'往后',context:'理解从哪里来，选择往哪里去。',build:endScene,score:3,at:47,gain:.46}
];
function next(n){if(busy||!chapters[n])return;busy=true;hideHot();choices([]);hint('');$('curtain').style.opacity=1;sound('wind');after(.65,()=>{clear();chapter=n;st.chapter=n;save();let c=chapters[n];$('chapter').textContent=c.year+' · '+c.age+' · '+c.name;c.build();score(c.score,c.at,c.gain);let initial=$('subtitle').textContent;say(c.context);after(4.2,()=>{if($('subtitle').textContent===c.context)say(initial);});let year=glyph(c.year,0,3.8,-12,6,n>=8?BLUE:GOLD);year.userData.alpha=.34;after(3.5,()=>tween(year.userData,{scatter:.7,alpha:0},2.5));$('curtain').style.opacity=0;});}
function prologue(){clear();mode='prologue';chapter=-1;st.chapter=0;try{localStorage.setItem('river-particle-v4',JSON.stringify(st));}catch{}$('chapter').textContent='此刻';score(0,9,.24);let phone=form('rotary',0,.4,-2,5,GOLD,8500);phone.userData.alpha=.35;let echo=glyph('稳',0,3.4,-3,3.6,GOLD);echo.userData.scatter=.65;reveal(echo,3);camera.position.set(0,1.6,10);look.set(0,1,-3);fly(V(0,1.6,7),V(0,1,-3),3);sound('ring');say('“别折腾。”');hint('点亮这句话。');hot(echo,'听见','enter-memory',()=>{busy=true;hideHot();say('');hint('');tween(echo.userData,{scatter:1.3,alpha:0},2.5);tween(phone.userData,{scatter:.9,alpha:0},2.5);fly(V(0,1.6,1),V(0,1,-6),2.8,()=>{busy=false;next(0);});},-1.2);}
let grain={};function grainScene(){mode='grain';lightBeam(V(2,4,-9),V(-1,-.6,9),1.2,0xd7bf91);grain={ticket:false,cash:false,queue:3,phase:0,waiting:false,meal:[0,0],amount:6};let clerk=form('person',0,2,-9,4,GOLD,5500);clerk.userData.alpha=.35;for(let i=0;i<3;i++){let p=form('person',i%2?.25:-.3,1.6,4-i*3.5,4.4,0xafa07e,6500);p.userData.alpha=.6;grain['person'+i]=p;}let room=[];for(let i=0;i<15000;i++){let side=i%2?-1:1;room.push(side*(3.5+rand()*.5),rand()*4.4-.8,rand()*24-10);}let walls=points(room,0x80745c,.022);walls.userData.alpha=.24;let roof=[];for(let i=0;i<5000;i++)roof.push((rand()-.5)*7,4+rand()*.25,rand()*24-10);points(roof,0xb0a187,.016).userData.alpha=.16;let shelf=[];for(let i=0;i<5000;i++)shelf.push((rand()-.5)*7,-.2+rand()*3,-8+(rand()-.5)*.2);let window=points(shelf,0x8c744b,.025);window.userData.alpha=.14;grain.ticketActor=form('ticket',1.1,1.25,8.1,1.8,GOLD,4300);grain.cashActor=form('money',-1.1,.65,8.1,1.8,GOLD,2800);grain.hand=form('grip',.65,.95,8.1,2.2,GOLD,8500);grain.hand.userData.alpha=.1;grain.bag=form('sack',.8,1.1,-6,2.4,GOLD,1900);grain.bag.userData.alpha=.58;hot(grain.ticketActor,'拿票','take-ticket',pickTicket,-.8);hot(grain.cashActor,'钱','pay-money',pay,-.8);hot(grain.bag,'窗口','window',queueForward,-.8);camera.position.set(0,1.6,14);look.set(0,1.1,-4);fly(V(0,1.65,11),V(0,1.3,-6),4);say('前面，还有三个人。');hint('点击票和钱，准备好再等窗口。');let dust=[];for(let i=0;i<2200;i++)dust.push((rand()-.5)*9,rand()*4,rand()*17-5);let air=points(dust,0xad9e86,.015);air.userData.alpha=.14;anim.push({tick(t){air.rotation.z=Math.sin(t*.035)*.018;return false;}});grain.started=time;}
function pickTicket(){if(grain.ticket)return;grain.ticket=true;grain.hand.userData.alpha=.9;sound('paper');hotspots.find(h=>h.b.dataset.action==='take-ticket').b.style.display='none';grain.ticketActor.rotation.z=-.12;move(grain.ticketActor,V(1.05,1.25,8.3),1.4);reveal(grain.hand,1.4);say('攥紧了。别弄丢。');hint('还需要付款的钱。');}
function pay(){if(grain.cash)return;grain.cash=true;sound('coin');hotspots.find(h=>h.b.dataset.action==='pay-money').b.style.display='none';move(grain.cashActor,V(.7,.9,8.35),1.2);grain.cashActor.scale.setScalar(.6);say('票和钱，一样不能少。');hint('点窗口，等叫到下一位。');}
function queueForward(){if(grain.phase>0)return;if(!grain.ticket||!grain.cash){say(!grain.ticket?'没有票，还不能领。':'有票，也要付钱。');sound('dull');return;}if(grain.waiting)return;if(grain.queue>0){grain.waiting=true;hint('等窗口叫到下一位。');sound('stamp');let i=3-grain.queue;let p=grain['person'+i];tween(p.userData,{scatter:.8,alpha:0},3);after(2.2,()=>{if(chapter!==0||grain.phase>0)return;grain.queue--;let z=11-(3-grain.queue)*3;fly(V(0,1.65,z),V(0,1.3,-6),3,()=>{grain.waiting=false;grain.ticketActor.position.z=z-2.6;grain.hand.position.z=z-2.5;grain.cashActor.position.z=z-2.55;say(grain.queue?['','前面，还有一个人。','前面，还有两个人。'][grain.queue]:'轮到你了。');hint(grain.queue?'点窗口，向前挪一步。':'按住票，把它递到窗口。');if(!grain.queue){hotspots.find(h=>h.b.dataset.action==='window').b.style.display='none';prepareDeliver();}});sound('step');});} }
function prepareDeliver(){grain.phase=1;choices([]);let b=hot(grain.ticketActor,'按住递票','deliver-ticket',()=>beginDelivery(true),-.5);b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);beginDelivery(false);};b.onpointerup=e=>{e.preventDefault();if(hold&&!hold.auto)cancelDelivery();};b.onpointercancel=cancelDelivery;b.onclick=e=>{if(e.detail===0)beginDelivery(true);};}
function beginDelivery(auto=false){if(grain.phase!==1||hold||paused||cam)return;hold={start:time,auto,origin:grain.ticketActor.position.clone()};hint('保持按住。让手里的票递过去。');sound('paper');let start=time;anim.push({tick(t){if(!hold||grain.phase!==1)return true;let k=clamp((t-start)/1.7);grain.ticketActor.position.lerpVectors(hold.origin,V(.1,1,-5.4),k*k);grain.hand.position.lerp(V(.5,.7,-4.5),.012);grain.ticketActor.userData.alpha=.7+k*.25;if(k>=1){hold=null;deliverTicket();return true;}return false;}});}
function cancelDelivery(){if(!hold||grain.phase!==1)return;grain.ticketActor.position.copy(hold.origin);hold=null;hint('按住票，递到窗口。');}
function deliverTicket(){if(grain.phase!==1)return;grain.phase=2;busy=true;hideHot();choices([]);musicLevel(.015,.8);sound('paper');say('手里的票，递了出去。');hint('等核验。');move(grain.ticketActor,V(0,.9,-5.5),2.2);move(grain.cashActor,V(.2,.6,-5.4),2.2);move(grain.hand,V(.5,.45,-4.2),2.2);fly(V(-.4,1.5,1),V(0,1,-6),3,()=>{sound('stamp');after(1.4,()=>musicLevel(.3,3));tween(grain.ticketActor.userData,{scatter:.7,alpha:0},1.2);tween(grain.cashActor.userData,{alpha:0},1);say('这一份，是一家人的口粮。');pour(V(.2,2.2,-6),V(.8,1.2,-6),1200,2,()=>{move(grain.bag,V(.6,.5,-1.2),2.5,()=>{busy=false;grain.phase=3;sound('grain');say('只领到这一袋。');hint('伸手接住，再带回家。');choices([['接住',takeBag],['再领一袋',()=>{sound('dull');say('票已经用掉了。');hint('手里没有下一份票。先接住这一袋。');}]]);});});});}
function pour(from,to,n,duration,done){let coords=[],start=time;for(let i=0;i<n;i++)coords.push(from.x+(rand()-.5)*.8,from.y,from.z+(rand()-.5)*.6);let p=points(coords,GOLD,.08);let attr=p.geometry.getAttribute('position');anim.push({tick(t){let k=(t-start)/duration;for(let i=0;i<n;i++){let f=clamp(k-(i/n)*.3),x=from.x+(to.x-from.x)*f,y=from.y+(to.y-from.y)*f-Math.sin(f*Math.PI)*.15,z=from.z+(to.z-from.z)*f;attr.setXYZ(i,x+(Math.sin(i*7)*.3)*(1-f*.7),y+Math.sin(i)*.18,z+Math.cos(i*9)*.2);}attr.needsUpdate=true;if(k>=1.3){tween(p.userData,{alpha:.12},1);if(done)done();return true;}}});return p;}
function takeBag(){busy=true;choices([]);sound('grain');move(grain.hand,V(.8,.1,-.9),1.5);move(grain.bag,V(.6,.35,-.8),1.5,()=>{say('带回去。还要想着明天。');tween(grain.hand.userData,{scatter:.6,alpha:0},2);tween(grain.bag.userData,{scatter:.5,alpha:0},2);fly(V(0,3,8),V(0,.2,0),3,mealScene);});}
function mealScene(){clear();mode='meal';grain.phase=4;let parent=form('person',-4,1,-5,4.5,GOLD,5500);parent.userData.alpha=.25;form('person',4,.9,-6,3.2,GOLD,3500).userData.alpha=.23;grain.source=form('sack',0,1,-2,2.6,GOLD,1400);grain.bowls=[form('bowl',-2.6,.1,0,3.4,GOLD,3800),form('bowl',2.6,.1,0,3.4,GOLD,3800)];grain.fills=[[],[]];hot(grain.bowls[0],'今晚','tonight',()=>measure(0),-.9);hot(grain.bowls[1],'明天','tomorrow',()=>measure(1),-.9);camera.position.set(0,3.4,8);look.set(0,.8,0);say('今晚吃多少，明天留多少？');hint('一袋分六份。点击两只碗，逐份舀进去。');grain.meal=[0,0];grain.amount=6;}
function measure(i){if(grain.amount<=0||busy)return;busy=true;grain.amount--;grain.meal[i]++;sound('grain');grain.source.scale.setScalar(.45+.55*grain.amount/6);let pos=grain.bowls[i].position;pour(V(0,1.6,-2),pos.clone().add(V(0,.08,0)),400,1.1,()=>{busy=false;if(!grain.amount){st.ration=grain.meal.slice();save();hideHot();say(grain.meal[1]?'留一点，明天还有。':'今晚吃完了。明天，怎么办？');hint('这是一段虚构的家庭记忆。');choices([['留在心里',()=>next(1)]]);}else hint(`还剩 ${grain.amount} 份。`);});}
function trainScene(){mode='train';lightBeam(V(-6,5,-8),V(4,-1,3),2,0xcfb993);let hand=form('hand',-2,-.8,4,3.2,GOLD,6500),bag=form('case',-2.4,-.2,2,3.4,GOLD,5500),train=form('train',-20,1,-4,11,GOLD,14000);hand.userData.alpha=.12;let paper=form('letter',3,.1,1,1.8,GOLD,2400);let platform=[];for(let i=0;i<4500;i++){let x=(rand()-.5)*55;platform.push(x,-1.2,-4+(rand()-.5)*.05);}points(platform,0xab946a,.032).userData.alpha=.38;let figures=[];for(let i=0;i<5;i++)figures.push(form('person',(i-2)*3,1.3,-10,3.5,GOLD,3200));let carry=false,letter=false,arrived=false;hot(bag,'提箱','carry-case',()=>{if(carry)return;carry=true;sound('step');reveal(hand,1);move(bag,V(-1.5,-.3,4),2);say('家，留在身后。');hint('可以留一封信。等车停稳，再上车。');},-.8);hot(paper,'留信','leave-letter',()=>{letter=true;sound('paper');tween(paper.userData,{scatter:.8,alpha:0},2);say('到了，给家里捎个信。');},-.6);hot(train,'上车','board-train',()=>{if(!carry){say('先提起自己的行李。');return;}if(!arrived){say('车还没停稳。');return;}hideHot();busy=true;sound('train');tween(bag.userData,{scatter:.5,alpha:0},2);tween(hand.userData,{alpha:0},2);fly(V(1,1.5,-3),V(8,1,-7),4,()=>{tween(train.userData,{scatter:.5,alpha:.12},5);figures.forEach(p=>tween(p.userData,{scatter:.4,alpha:0},5));let city=[];for(let i=0;i<12500;i++){let x=(rand()-.5)*35,cluster=Math.floor((x+17.5)/2),height=2+(cluster*17%9);city.push(x,rand()*height-1.1,-17+(rand()-.5)*.5);}let sky=points(city,GOLD,.027);reveal(sky,5);say(letter?'联系还在。路，要自己走。':'你离开了，他们仍会担心。');fly(V(0,2,7),V(0,3,-16),6,()=>{busy=false;choices([['往前走',()=>next(3)]]);});});},-.8);camera.position.set(0,1.5,10);look.set(0,.8,-4);fly(V(0,1.6,7),V(0,1,-4),3);move(train,V(1,1,-4),7,()=>{arrived=true;sound('train');});sound('train');say('第一次出远门。');hint('提起箱子。列车正在进站。');}
function keyScene(){mode='key';corridor(15,24);lightBeam(V(5,3.5,-7),V(1,-.5,2),1.2,0xe3b773);let key=form('key',0,.1,3,2.7,GOLD,5200),door=form('door',4,1,-5,5.5,GOLD,8000);key.userData.alpha=.1;let coins=[];for(let i=0;i<12;i++){let p=form('money',(i%6-2.5)*.75,1.6-Math.floor(i/6)*.7,-1,1.05,GOLD,300);coins.push(p);}let allocated=false,taken=false;let wall=glyph('家',4,1,-8,3.3,GOLD);wall.userData.alpha=.16;camera.position.set(0,2.2,13);look.set(0,1,-4);fly(V(0,1.7,9),V(0,1,-3),4);say('成家之后，手里的钱要分给很多明天。');hint('这些光点，是一家人的余量。');choices([['把更多钱放进房子',()=>allocate('home',10)],['住小一点，留一些余量',()=>allocate('margin',7)]]);function allocate(kind,n){if(allocated)return;allocated=true;busy=true;st.path=kind;choices([]);sound('paper');coins.slice(0,n).forEach((p,i)=>after(i*.12,()=>move(p,V(4,.2,-5),1.8,()=>tween(p.userData,{scatter:.25,alpha:0},1))));after(3,()=>{busy=false;reveal(key,1.5);say(kind==='home'?'家安稳了。手里的余量，也少了。':'住处小一些。还有应对明天的余量。');hint('拿起钥匙，打开这扇门。');});}hot(key,'拿钥匙','take-key',()=>{if(!allocated){say('先决定，给住处留多少。');return;}taken=true;sound('key');move(key,V(2,.2,3),1.6);say('钥匙很轻，责任很重。');},-1);hot(door,'开门','open-house',()=>{if(!taken){say('钥匙还不在手里。');return;}busy=true;hideHot();choices([]);sound('key');move(key,V(4.5,.7,-4.9),2);fly(V(3,1.6,1),V(5,1,-5),3,()=>{tween(door.userData,{scatter:1.1,alpha:.1},4);tween(key.userData,{alpha:0},2);let warm=[];for(let i=0;i<9000;i++){let a=rand()*Math.PI*2,r=Math.sqrt(rand())*5;warm.push(5+Math.cos(a)*r,.5+Math.sin(a)*r*.55,-7+(rand()-.5)*3);}let p=points(warm,0xdea868,.027);reveal(p,4);fly(V(5,1.6,-3),V(5,1,-7),5,()=>{busy=false;say('从此，担心的不只自己。');hint('一扇门里，还有一个正在长大的孩子。');choices([['往后的日子',()=>next(5)]]);});});},-2);}
function nowScene(){mode='now';let phone=form('phone',-4,1,-1,3.8,BLUE,5000),clock=form('clock',0,1,-4,3.4,GOLD,6000),breath=form('breath',4,1,-1,4,GOLD,5000);let feed=[];for(let i=0;i<15;i++){let p=glyph(['还有消息','别人更快','不能停'][i%3],(rand()-.5)*16,rand()*5,-6-rand()*8,3,BLUE);p.userData.alpha=.3;feed.push(p);}let quiet=false,rest=false,applications=0;hot(phone,'投递','send-application',()=>{if(quiet)return;applications++;sound('paper');let result=glyph(applications%2?'待回复':'未通过',0,2,-3,3.2,BLUE);reveal(result,.6);after(2,()=>tween(result.userData,{scatter:.8,alpha:0},2));say(applications===1?'投出去了。结果，还不由你决定。':'努力是真的，不确定也是真的。');if(applications>=2){hotspots.find(h=>h.b.dataset.action==='send-application').b.style.display='none';quietButton.style.display='block';hint('给今天的自己，留一个暂停。');}},-.1);anim.push({tick(t){if(!quiet)feed.forEach((p,i)=>p.position.x+=Math.sin(t+i)*.004);return false;}});let quietButton=hot(phone,'静音','quiet-phone',()=>{quiet=true;sound('off');feed.forEach(p=>tween(p.userData,{scatter:1,alpha:0},2.5));phone.userData.alpha=.16;say('先让消息，安静一会儿。');hint('你的注意力，也属于你。');},-1.4);quietButton.style.display='none';hot(clock,'休息','rest-clock',()=>{if(!quiet){say('消息，还在占着你的时间。');return;}rest=true;sound('breath');clock.rotation.z=-.2;tween(clock.userData,{scatter:.3,alpha:.22},2);say('不用耗尽自己，证明努力。');hint('再找回自己的节奏。');},-1.5);hot(breath,'自己的节奏','own-step',()=>{if(!rest){say('先留一点休息。');return;}hideHot();reveal(breath,2);say('机会更多，确定的答案却未必更多。');hint('下一步，不必等所有人认可。');choices([['拿回自己的日子',()=>next(9)]]);},-1.4);camera.position.set(0,2,13);look.set(0,1,-3);fly(V(0,1.8,9),V(0,1,-3),4);say('消息更快。比较更近。');hint('点击投递。把机会交出去，也看见不确定。');}
let phoneTurn=0;function phoneScene(){mode='call';lightBeam(V(-3,3,-8),V(2,-.7,1),1.6,GOLD);form('person',-5,1,-7,4,GOLD,6000).userData.alpha=.35;form('person',5,1,-7,4,BLUE,6000).userData.alpha=.35;let phone=form('rotary',0,.4,-1,5,GOLD,9000);let link=[];for(let i=0;i<5000;i++){let x=(rand()-.5)*12;link.push(x,.4+Math.sin(x)*.08,-4+Math.sin(x*.4));}points(link,GOLD,.03).userData.alpha=.35;camera.position.set(0,1.5,10);look.set(0,.8,-2);fly(V(0,1.7,7),V(0,.8,-2),3);sound('ring');phoneTurn=0;say('“我是怕你吃亏。”');hint('你想怎样回答？');phoneChoices();}
function phoneChoices(){if(phoneTurn===0)choices([['先听完',()=>answer('listen')],['解释处境',()=>answer('facts')],['不想再争',()=>answer('pause')]]);if(phoneTurn===1)choices([['决定自己承担',()=>answer('own')],['商量有限支持',()=>answer('support')],['必须让他理解',()=>answer('force')]]);}
function answer(kind){sound('answer');if(kind==='force'){say('有些想法，今天仍改变不了。');hint('可以选择继续沟通，也可以先保护自己。');choices([['先过好自己的生活',()=>answer('own')],['留一点沟通',()=>answer('support')]]);return;}if(phoneTurn===0){phoneTurn=1;st.boundary=kind;fly(V(kind==='pause'?3:-3,1.7,7),V(0,1,-4),3);say(kind==='pause'?'“我们先停一会儿。”':kind==='facts'?'“我也担心，我有自己的处境。”':'“我听见你的担心了。”');hint('听见，不等于必须同意。');phoneChoices();}else{st.decision=kind;say(kind==='own'?'“这一步，我来承担。”':'“能支持多少，我们说具体。”');hint('父母未必改变。生活仍要继续。');choices([['把日子握回手里',()=>next(10)]]);}}
function endScene(){mode='end';let a=form('person',-5,1,-5,4.6,GOLD,9000),b=form('person',5,1,-5,4.6,BLUE,9000);a.userData.alpha=b.userData.alpha=.35;['省','稳','家'].forEach((t,i)=>glyph(t,-5,2.1-i*.8,-4.75,.68,GOLD));['选','界','我'].forEach((t,i)=>glyph(t,5,2.1-i*.8,-4.75,.68,BLUE));let river=[];for(let i=0;i<16000;i++){let x=(rand()-.5)*13;river.push(x,-.5+Math.sin(x*.4)*.16,-3+(rand()-.5)*1.4);}let r=points(river,GOLD,.023);r.userData.alpha=.42;let clock=form('clock',-2.8,.5,1,2.1,BLUE,4800),margin=form('money',0,.4,1,1.7,GOLD,3200),phone=form('phone',2.8,.5,1,2.1,BLUE,4700);let chosen=false;function choose(kind){if(chosen)return;chosen=true;st.future=kind;save();hideHot();busy=true;[clock,margin,phone].forEach(p=>tween(p.userData,{scatter:.7,alpha:0},3));say(kind==='time'?'给自己留时间。':'reserve'===kind?'给生活留一点余量。':'把边界说清楚。');hint('');let path=[];for(let i=0;i<17000;i++){let k=rand(),width=.15+k*1.1;path.push(5+Math.sin(k*3.14)*4+(rand()-.5)*width,-1+(rand()-.5)*.1,-5-k*35);}let road=points(path,BLUE,.026);reveal(road,4);fly(V(1,2.3,12),V(5,0,-11),5,()=>{say('有些想法，你改变不了。');after(4,()=>{say('但日子，可以自己过。');fly(V(0,4,20),V(4,.4,-12),8);after(7.5,()=>{busy=false;say('如果他们始终不理解，你会怎样过好自己的生活？');hint('');choices([['再走一遍',()=>{st={chapter:0,ration:[0,0],path:'',boundary:'',decision:''};prologue();}],['音乐与资料',showSources]]);});});});}hot(clock,'留时间','future-time',()=>choose('time'),-.8);hot(margin,'留余量','future-reserve',()=>choose('reserve'),-.8);hot(phone,'说边界','future-boundary',()=>choose('boundary'),-.8);camera.position.set(0,1.7,11);look.set(0,.8,-4);fly(V(0,2.4,13),V(0,1,-4),4);say('理解他们从哪里来。决定自己往哪里去。');hint('你想先为自己留住什么？');save();}
function showSources(){let wasPaused=paused;if(!paused)pause(true);$('sources').style.display='flex';$('sources').innerHTML=`<div class="credits-inner"><button id="closeCredits" aria-label="关闭资料">×</button><h2>音乐与时代依据</h2><p>人物以1975年出生为示意；孩子以2003年出生为示意。家庭故事为虚构，各地、城乡与家庭经历不同。</p><h3>Music by Scott Buckley</h3><p>'Signal to Noise', 'Signal to Noise — No Piano Melody', 'Undertow', 'Penumbra' by Scott Buckley — released under CC-BY 4.0.<br><a target="_blank" rel="noopener" href="https://www.scottbuckley.com.au">www.scottbuckley.com.au</a> · <a target="_blank" rel="noopener" href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a><br>游戏做了片段进入、音量包络与交叉淡化。</p><p>电话、列车：Joseph SARDIN / BigSoundBank（CC0）；纸张：alec_mackay / Freesound（CC0）；转盘电话：alexdarek / Freesound（CC0）。转场等取自HyperFrames媒体库（Pixabay Content License）。声音为戏剧化配置，不是中国历史现场录音。</p><h3>时间线</h3><p><a target="_blank" rel="noopener" href="https://www.mof.gov.cn/zhuantihuigu/czgg0000_1/czgg0000/200811/t20081106_88273.htm">票证与1993年粮食供应变化</a><br><a target="_blank" rel="noopener" href="https://www.moe.gov.cn/jyb_xwfb/xw_zt/moe_357/s3581/moe_2669/moe_2921/tnull_51639.html">1986年九年义务教育推行</a><br><a target="_blank" rel="noopener" href="https://www.gov.cn/gongbao/content/2003/content_62011.htm">1998年以来国企改革与再就业</a><br><a target="_blank" rel="noopener" href="https://www.gov.cn/gongbao/shuju/1998/gwyb199817.pdf">1998年住房制度改革</a><br><a target="_blank" rel="noopener" href="https://www.stats.gov.cn/sj/zxfb/202303/t20230301_1919494.html">2008年金融危机背景</a><br><a target="_blank" rel="noopener" href="https://www.cac.gov.cn/2016-01/22/c_1117853351.htm">2015年移动互联网与支付</a><br><a target="_blank" rel="noopener" href="https://www.moe.gov.cn/srcsite/A15/s3265/202003/t20200306_428194.html">2020年疫情与求职</a></p></div>`;$('closeCredits').onclick=()=>{$('sources').style.display='none';if(!wasPaused)pause(false);};}

// One life, from 1978 to 2026. Context stays in the small date and one sentence.
function scrubHot(actor,label,id,onProgress,onFinish,axis='x',pixels=180){let active=false,start=0,k=0;let b=hot(actor,label,id,()=>auto());b.dataset.gesture='drag';function auto(){if(active||paused||busy||cam)return;active=true;let t=time;anim.push({tick(now){if(!active)return true;k=clamp((now-t)/1.8);onProgress(k);if(k===1){active=false;onFinish();return true;}return false;}});}b.onpointerdown=e=>{if(paused||busy||cam)return;e.preventDefault();b.setPointerCapture(e.pointerId);active=true;k=0;start=axis==='x'?e.clientX:e.clientY;b.style.cursor='grabbing';};b.onpointermove=e=>{if(!active)return;let v=axis==='x'?e.clientX:e.clientY;k=clamp(Math.abs(v-start)/Math.min(pixels,innerWidth*.3));onProgress(k);if(k>=1){active=false;b.style.cursor='pointer';onFinish();}};b.onpointerup=e=>{e.preventDefault();active=false;b.style.cursor='pointer';if(k<1)hint('保持按住，再慢慢拖动。');};b.onpointercancel=()=>active=false;b.onclick=e=>{if(e.detail===0)auto();};return b;}
function schoolScene(){mode='school';corridor(12,25);lightBeam(V(-4,4,-4),V(1,-.5,2),1.6);let seats=[];for(let row=0;row<4;row++)for(let col=0;col<5;col++){let a=[];for(let i=0;i<550;i++)a.push((rand()-.5)*1.5+col*2.2-4.4,.4+rand()*.04,-row*3-5+(rand()-.5));let p=points(a,GOLD,.022);p.userData.alpha=.3;seats.push(p);}let lamp=form('lamp',-3.8,1.8,-2,2.6,GOLD,4200),book=form('book',0,.9,1,4.4,GOLD,10000),pencil=form('pencil',2.5,.5,2,2.5,GOLD,4000);let road=glyph('路',0,2,-5,3.8,GOLD);road.userData.alpha=0;book.rotation.y=-.45;let opened=false,written=false;hot(book,'翻开','open-book',()=>{if(opened)return;opened=true;sound('paper');tween(book.rotation,{y:0},2);fly(V(0,2,7),V(0,1.1,0),3);say('那时，一本书也能装下一条出路。');hint('按住笔，拖动。写下这一笔。');hotspots.find(h=>h.b.dataset.action==='open-book').b.style.display='none';},-.6);scrubHot(pencil,'写下','write-path',k=>{if(!opened)return;pencil.position.x=2.5-k*4;pencil.rotation.z=k*.25;road.userData.alpha=k*.7;lamp.userData.alpha=.65+k*.2;},()=>{if(!opened){say('先翻开那本书。');return;}if(written)return;written=true;hideHot();sound('paper');say('“读下去，往外走。”');hint('家人的希望，也成了你的责任。');let thread=[];for(let i=0;i<5500;i++){let z=rand()*18-17;thread.push(Math.sin(z*.3)*.7,-.5+rand()*.08,z);}let p=points(thread,GOLD,.03);reveal(p,3);morph(pencil,'case',V(0,1,-6),2.8,4);fly(V(-1,1.6,8),V(0,1,-7),4,()=>choices([['走向远方',()=>next(2)]]));},'x',200);camera.position.set(0,2.6,12);look.set(0,1,-3);fly(V(0,2,9),V(0,1.3,-2),4);say('书页旧了，希望还在。');hint('点击书本。');}
function workScene(){mode='work';corridor(18,40,0xbaae94);lightBeam(V(6,6,-12),V(-5,-1,2),2,0xcebf9c);let gears=[],conveyor=[];for(let k=0;k<5;k++){let a=[];for(let i=0;i<3600;i++){let angle=rand()*Math.PI*2,r=1.1+(Math.sin(angle*13)>.1?.35:.18)*rand();a.push(Math.cos(angle)*r,Math.sin(angle)*r,(rand()-.5)*.18);}let p=points(a,0xccb186,.037);p.position.set((k-2)*4,2.7,-9);gears.push(p);}for(let i=0;i<11000;i++)conveyor.push((rand()-.5)*24,-.3+rand()*.18,rand()*9-9);let belt=points(conveyor,GOLD,.023);belt.userData.alpha=.35;let staff=[];for(let i=0;i<5;i++){let p=form('person',(i-2)*3.4,1,-12,3.5,0xbeaf92,4300);p.userData.alpha=.3;staff.push(p);}let badge=form('badge',1,.7,2,2.8,GOLD,7000),hand=form('hand',1,-.1,2,2.9,GOLD,6500);hand.userData.alpha=.2;let running=true,punched=false;anim.push({tick(t){if(running){gears.forEach((p,i)=>p.rotation.z=t*(i%2?-.32:.32));belt.position.x=Math.sin(t*.3)*2;}return false;}});hot(badge,'打卡','punch-work',()=>{if(punched)return;punched=true;hideHot();busy=true;reveal(hand,1);move(badge,V(0,1,-5),2);fly(V(-1,1.7,5),V(0,1.3,-9),4);sound('stamp');after(2.8,()=>{running=false;musicLevel(.03,1);sound('dull');staff.forEach(p=>tween(p.userData,{scatter:.5,alpha:.03},4));gears.forEach(p=>tween(p.userData,{scatter:.8,alpha:.06},4));tween(belt.userData,{alpha:.03},3);say('这一次，工牌换不来工资。');hint('这段经历，来自一个虚构的受改革影响家庭。');});after(6.5,()=>{busy=false;musicLevel(.27,3);say('身份突然不稳了。明天还得继续。');hint('选一个方向，重新开始。');choices([['找一份新工作',()=>restartWork('job')],['学一门手艺',()=>restartWork('skill')]]);});},-1);function restartWork(path){busy=true;st.workPath=path;choices([]);sound('paper');morph(badge,path==='skill'?'pencil':'letter',V(0,.8,-2),3,4);tween(hand.userData,{scatter:.35,alpha:.12},3);memoryWord('重新开始',0,3,-7,5);fly(V(0,2,9),V(0,1,-3),5,()=>{busy=false;say(path==='skill'?'从靠一张工牌，到靠自己的手艺。':'从等单位安排，到自己寻找机会。');hint('那句“找个稳定的”，有时从这里长出来。');choices([['成家以后',()=>next(4)]]);});}camera.position.set(0,1.7,13);look.set(0,1.6,-8);fly(V(0,1.7,8),V(0,1.8,-8),4);say('上班、领工资。以为可以一直这样。');hint('把工牌递向打卡处。');}
function familyScene(){mode='family';corridor(13,24);lightBeam(V(3,3.5,-6),V(0,-.5,1),1.2);let parent=form('person',-4,1.1,-7,4.7,GOLD,7800),child=form('person',3.4,.3,-5,2.9,GOLD,6000),book=form('book',3.4,-.1,-3,2.2,GOLD,4800),clock=form('clock',-3,1.3,-3,2.8,GOLD,6000);let lights=[];for(let i=0;i<3;i++){let a=[];for(let j=0;j<650;j++){let angle=rand()*Math.PI*2,r=rand()*.16;a.push(Math.cos(angle)*r,Math.sin(angle)*r,(rand()-.5)*.1);}let p=points(a,GOLD,.04);p.position.set((i-1)*.65,3,-3);lights.push(p);}let evening=3,money=0,together=0;let city=[];for(let i=0;i<8000;i++){let x=(rand()-.5)*28;city.push(x,rand()*(2+(Math.floor(x+14)*13%6)),-16);}let jobs=points(city,GOLD,.018);jobs.userData.alpha=.23;after(3,()=>tween(jobs.userData,{alpha:.09,scatter:.12},4));function spend(what){if(!evening)return;busy=true;evening--;let lamp=lights[evening];tween(lamp.userData,{scatter:.7,alpha:0},2);clock.rotation.z-=.45;if(what==='work'){money++;sound('step');move(parent,V(-6,1,-9),1.5);let cash=form('money',-4,.8,-4,1.4,GOLD,600);move(cash,V(3.4,.1,-3),2.2,()=>tween(cash.userData,{alpha:.1},1));say('多一份收入，少一段陪伴。');}else{together++;sound('paper');move(parent,V(1.1,.8,-5),1.8);child.userData.alpha=.7;let warmth=[];for(let i=0;i<2300;i++){let a=rand()*Math.PI*2,r=Math.sqrt(rand())*1.7;warmth.push(2.1+Math.cos(a)*r,.4+Math.sin(a)*r,-5+(rand()-.5));}reveal(points(warmth,0xf5ca8c,.027),2);say('这一个晚上，留给孩子。');}after(2.8,()=>{busy=false;if(evening){hint('还有 '+evening+' 个晚上。收入与陪伴，都有重量。');}else{st.parenting={money,together};save();hideHot();say(together?'“愿你以后，有更多选择。”':'你撑住了开支。孩子也在等你。');hint('每一种选择，都有没能兼顾的东西。');choices([['再过几年',()=>next(6)]]);}});}hot(clock,'加班','family-work',()=>spend('work'),-1.1);hot(book,'陪孩子','family-time',()=>spend('time'),-.7);camera.position.set(0,2,12);look.set(0,1,-5);fly(V(0,1.8,9),V(0,1,-4),4);say('白天要挣钱，晚上还想陪他。');hint('三个晚上，逐个决定留给谁。');}
function digitalScene(){mode='digital';let parent=form('person',-4,1,-7,4.6,GOLD,7000),young=form('person',4,1,-7,3.7,BLUE,6000),phone=form('phone',0,.9,-1,4.5,BLUE,8200),hand=form('hand',-1,-.5,1,2.8,GOLD,6500);hand.rotation.z=.3;let code=[];for(let y=0;y<29;y++)for(let x=0;x<29;x++){let finder=(x<7&&y<7)||(x>21&&y<7)||(x<7&&y>21);if(finder||rand()>.52)for(let j=0;j<5;j++)code.push((x-14)*.039+(rand()-.5)*.018,.9+(14-y)*.039+(rand()-.5)*.018,-.92+(rand()-.5)*.025);}let qr=points(code,BLUE,.044);let scan=[];for(let i=0;i<1400;i++)scan.push((rand()-.5)*1.5,0,(rand()-.5)*.025);let beam=points(scan,0xd1ecdf,.033);beam.position.set(0,1.5,-.8);beam.userData.alpha=0;let scanned=false;let scanButton=scrubHot(phone,'往下扫','learn-phone',k=>{beam.userData.alpha=.7;beam.position.y=1.55-k*1.3;hand.position.y=-.5+k*.5;qr.userData.alpha=.45+k*.4;},()=>{if(scanned)return;scanned=true;hideHot();sound('off');tween(beam.userData,{alpha:0},1.5);tween(qr.userData,{scatter:.4,alpha:0},2);let pulse=[];for(let i=0;i<5000;i++){let x=(rand()-.5)*8;pulse.push(x,1+Math.sin(x*.8)*.4,-4+(rand()-.5)*.1);}let p=points(pulse,GOLD,.029);reveal(p,2.5);say('“这次，你教我一下。”');hint('曾经牵你的手，也会有跟不上的时候。');fly(V(-2,1.8,8),V(0,1,-3),4,()=>choices([['继续往后走',()=>next(7)]]));},'y',140);camera.position.set(0,1.8,12);look.set(0,1,-3);fly(V(0,1.7,8),V(0,1,-2),4);say('小小的屏幕，像一扇陌生的门。');hint('按住手机上的字，向下拖动。');}
function pandemicScene(){mode='pandemic';lightBeam(V(-3,4,-16),V(2,-.5,4),1.5,BLUE);let window=form('window',0,1,-1,7,GOLD,14000);window.userData.alpha=.45;let city=[];for(let i=0;i<17000;i++){let x=(rand()-.5)*36,h=2+(Math.floor(x+18)*17%10);city.push(x,rand()*h-1,-18+(rand()-.5)*3);}let distant=points(city,0x718e97,.022);distant.userData.alpha=.2;let route=[];for(let i=0;i<8000;i++){let z=rand()*22-14;route.push(Math.sin(z*.24)*2,-1.1+rand()*.04,z);}let road=points(route,GOLD,.024);road.userData.alpha=.22;after(2,()=>tween(road.userData,{scatter:.6,alpha:0},4));let phone=form('phone',-3,.6,2,2.9,BLUE,5500),bowl=form('bowl',0,-.1,3,2.3,GOLD,5000),cash=form('money',3,.3,2,2.1,GOLD,2600);let done=new Set();function check(){if(done.size<3)return;hideHot();say('被打断的计划，要重新接起来。');hint('孩子也经历着同一场不确定。');choices([['走到今天',()=>next(8)]]);}hot(phone,'联系家人','check-family',()=>{if(done.has('call'))return;done.add('call');sound('dial');let hand=form('hand',-3,.2,-12,3.3,GOLD,5000);reveal(hand,3);let thread=[];for(let i=0;i<4500;i++){let k=rand();thread.push(-3,1+Math.sin(k*Math.PI)*1.5,2-k*14);}let p=points(thread,BLUE,.027);reveal(p,2);say('“你那边，还好吗？”');phone.userData.alpha=.3;hotspots.find(h=>h.b.dataset.action==='check-family').b.style.display='none';check();},-1);hot(bowl,'今天的饭','today-meal',()=>{if(done.has('meal'))return;done.add('meal');busy=true;sound('grain');pour(V(.2,1.2,3),V(0,.05,3),650,1.2,()=>{busy=false;hotspots.find(h=>h.b.dataset.action==='today-meal').b.style.display='none';say('日子暂时慢了，饭还要一顿顿做。');check();});},-.8);hot(cash,'明天的开支','keep-reserve',()=>{if(done.has('money'))return;done.add('money');sound('coin');move(cash,V(2.3,.2,1),2);say(st.path==='margin'?'从前留的一点余量，现在接住了生活。':'账单不会暂停。先把开支排清楚。');hotspots.find(h=>h.b.dataset.action==='keep-reserve').b.style.display='none';check();},-1);camera.position.set(0,1.7,12);look.set(0,1,-5);fly(V(0,1.7,8),V(0,1,-5),4);say('远方，突然去不了了。');hint('联系家人，照顾今天，留出明天。');}

const scoreFiles=['score-memory','score-tension','score-change','score-after'];
const scoreTitles=['Signal to Noise','Signal to Noise · No Piano Melody','Undertow','Penumbra'];
let ac=null,bus=null,musicOut=null,audioMeter=null,recordDest=null,tracks=[],trackGains=[],current=-1,musicTarget=.3,sfxActive=new Set();
function initAudio(){if(ac){ac.resume();return;}ac=new(window.AudioContext||window.webkitAudioContext)();let limiter=ac.createDynamicsCompressor(),mixLift=ac.createGain();mixLift.gain.value=2.8;mixLift.connect(limiter);limiter.threshold.value=-5;limiter.knee.value=8;limiter.ratio.value=8;limiter.attack.value=.006;limiter.release.value=.28;audioMeter=ac.createAnalyser();audioMeter.fftSize=2048;limiter.connect(audioMeter);audioMeter.connect(ac.destination);recordDest=ac.createMediaStreamDestination();limiter.connect(recordDest);bus=ac.createGain();bus.gain.value=.65;bus.connect(mixLift);musicOut=ac.createGain();musicOut.gain.value=.3;musicOut.connect(mixLift);for(let i=0;i<scoreFiles.length;i++){let a=new Audio(window.LOCAL_SCORES?.[i]||'assets/'+scoreFiles[i]+'.mp3');a.loop=true;a.preload='metadata';a.volume=1;let source=ac.createMediaElementSource(a),gain=ac.createGain();gain.gain.value=0;source.connect(gain).connect(musicOut);tracks.push(a);trackGains.push(gain);}ac.resume();}
function gainTo(param,value,seconds){if(!ac)return;let t=ac.currentTime;param.cancelScheduledValues(t);param.setValueAtTime(param.value,t);param.linearRampToValueAtTime(value,t+seconds);}
function musicLevel(level,seconds=2){musicTarget=level;if(musicOut)gainTo(musicOut.gain,muted?0:level,seconds);}
function score(i,at=0,level=.32){if(!ac)return;let old=current;current=i;tracks[i].currentTime=at;tracks[i].play().catch(()=>{});musicLevel(level,2.5);trackGains.forEach((g,j)=>gainTo(g.gain,j===i?1:0,j===i?3:2.6));after(3.2,()=>{if(current===i)tracks.forEach((a,j)=>{if(j!==i)a.pause();});});}
function recorded(type,volume=.35,pan=0){if(!ac||muted||paused)return false;let name={wind:'transition',dull:'change',off:'notification',answer:'dial'}[type]||type;if(!['paper','dial','train','transition','change','click','notification','ring','rail'].includes(name))return false;let a=new Audio(window.LOCAL_SFX?.[name]||'assets/sfx/'+name+'.mp3');a.volume=1;let src=ac.createMediaElementSource(a),g=ac.createGain(),p=ac.createStereoPanner();g.gain.value=volume;p.pan.value=pan;src.connect(g).connect(p).connect(bus);sfxActive.add(a);a.onended=()=>{src.disconnect();g.disconnect();p.disconnect();sfxActive.delete(a);};a.onerror=a.onended;a.play().catch(()=>a.onended());return true;}
function tone(freq,d,g=.12,delay=0,pan=0){if(!ac||muted||paused)return;let o=ac.createOscillator(),v=ac.createGain(),p=ac.createStereoPanner();o.type='sine';o.frequency.value=freq;v.gain.setValueAtTime(.001,ac.currentTime+delay);v.gain.linearRampToValueAtTime(g,ac.currentTime+delay+.02);v.gain.exponentialRampToValueAtTime(.001,ac.currentTime+delay+d);p.pan.value=pan;o.connect(v).connect(p).connect(bus);o.start(ac.currentTime+delay);o.stop(ac.currentTime+delay+d+.1);}
function noise(d,g=.2,cut=2200,pan=0){if(!ac||muted||paused)return;let b=ac.createBuffer(1,ac.sampleRate*d,ac.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=(rand()-.5)*g*Math.sin(Math.PI*i/a.length);let s=ac.createBufferSource(),f=ac.createBiquadFilter(),p=ac.createStereoPanner();s.buffer=b;f.type='lowpass';f.frequency.value=cut;p.pan.value=pan;s.connect(f).connect(p).connect(bus);s.start();}
function sound(type){if(type==='paper'){recorded('paper',.43,.3);return;}if(type==='train'){recorded('train',.4,-.45);recorded('rail',.2,-.3);return;}if(type==='ring'){recorded('ring',.42,-.15);return;}if(type==='answer'||type==='dial'){recorded('dial',.34);return;}if(type==='wind'){recorded('transition',.09);return;}if(type==='dull'){recorded('change',.13);return;}if(type==='click'){recorded('click',.18);return;}if(type==='off'){recorded('notification',.15);return;}if(type==='paper')noise(.6,.3,4200,.35);else if(type==='grain')noise(.8,.35,3200,.2);else if(type==='step'){noise(.18,.5,550,-.2);setTimeout(()=>noise(.18,.4,500,.2),380);}else if(type==='stamp'){noise(.14,.6,750,-.5);tone(100,.23,.1);}else if(type==='train'){for(let i=0;i<8;i++)setTimeout(()=>noise(.12,.25,1000,i%2?.5:-.5),i*220);tone(370,1.4,.07,0,-.65);tone(553,1.4,.06,.07,-.65);}else if(type==='coin'||type==='key'){tone(1430,.45,.1,.02,.3);tone(2110,.32,.04,.07,.25);}else if(type==='ring'){[0,.5,1].forEach(t=>{tone(440,.27,.09,t);tone(480,.27,.08,t);});}else if(type==='dull'){tone(70,1,.15);noise(.15,.3,500);}else if(type==='wind')noise(1.6,.18,750);else if(type==='grip'){q.moveTo(226,490);q.lineTo(203,364);q.bezierCurveTo(182,337,180,301,204,272);q.bezierCurveTo(223,248,241,245,254,263);q.bezierCurveTo(266,283,256,302,239,304);q.bezierCurveTo(261,321,307,304,306,277);q.lineTo(301,227);q.bezierCurveTo(298,202,322,195,329,220);q.lineTo(343,284);q.bezierCurveTo(350,305,352,340,329,372);q.lineTo(316,490);q.closePath();q.fill();q.beginPath();q.moveTo(265,269);q.bezierCurveTo(237,243,211,216,222,200);q.bezierCurveTo(235,182,260,202,278,220);q.bezierCurveTo(257,183,246,159,263,151);q.bezierCurveTo(282,144,296,171,304,196);q.stroke();}
if(type==='book'){q.lineWidth=6;q.moveTo(255,150);q.bezierCurveTo(205,122,118,134,74,152);q.lineTo(74,397);q.bezierCurveTo(142,374,204,389,255,421);q.bezierCurveTo(305,389,380,374,438,397);q.lineTo(438,152);q.bezierCurveTo(370,133,302,128,255,150);q.lineTo(255,421);q.stroke();for(let j=0;j<5;j++){q.moveTo(110,205+j*32);q.lineTo(210,209+j*32);q.moveTo(296,209+j*32);q.lineTo(398,202+j*32);}q.stroke();}
if(type==='pencil'){q.moveTo(218,441);q.lineTo(228,90);q.lineTo(279,90);q.lineTo(289,441);q.lineTo(253,484);q.closePath();q.stroke();q.moveTo(251,91);q.lineTo(251,434);q.stroke();}
if(type==='lamp'){q.lineWidth=5;q.moveTo(202,100);q.lineTo(310,100);q.lineTo(349,212);q.lineTo(157,212);q.closePath();q.stroke();q.moveTo(254,212);q.lineTo(254,400);q.moveTo(173,410);q.lineTo(334,410);q.stroke();}
if(type==='letter'){q.lineWidth=5;q.strokeRect(62,146,388,238);q.moveTo(62,146);q.lineTo(256,283);q.lineTo(450,146);q.moveTo(62,384);q.lineTo(196,271);q.moveTo(450,384);q.lineTo(312,270);q.stroke();}
if(type==='badge'){q.lineWidth=5;q.strokeRect(130,102,252,353);q.strokeRect(213,79,86,45);q.beginPath();q.ellipse(256,213,42,48,0,0,Math.PI*2);q.stroke();q.moveTo(193,301);q.bezierCurveTo(198,247,312,247,318,301);q.stroke();q.font='38px FilmSong';q.textAlign='center';q.fillText('职工',256,384);}
if(type==='window'){q.lineWidth=5;q.strokeRect(77,53,358,409);q.moveTo(256,53);q.lineTo(256,462);q.moveTo(77,244);q.lineTo(435,244);q.stroke();}
if(type==='rice'){q.lineWidth=5;for(let i=0;i<23;i++){q.beginPath();let x=110+(i*83%295),y=156+(i*61%225);q.ellipse(x,y,8,19,(i%5)*.3,0,Math.PI*2);q.stroke();}}
if(type==='breath')noise(1.2,.15,900);else if(type==='answer'){tone(261.63,1.1,.09);tone(392,1.2,.04,.12);}else tone(640,.18,.025);}
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}resize();addEventListener('resize',resize);
function loop(now){requestAnimationFrame(loop);let dt=last?Math.min((now-last)/1000,.3):0;last=now;if(paused)return;time+=dt;if(cam){let c=cam,k=clamp((time-c.start)/c.dur),e=k*k*(3-2*k);camera.position.lerpVectors(c.a,c.b,e);camera.position.y+=Math.sin(k*Math.PI)*.12;look.lerpVectors(c.c,c.d,e);if(k>=1){cam=null;if(c.done)c.done();}}camera.lookAt(look);let previous=anim;anim=[];previous.forEach(a=>{if(!a.tick(time))anim.push(a);});ambient.rotation.y=time*.001;actors.forEach(p=>{p.material.uniforms.uTime.value=time;p.material.uniforms.uOpacity.value=p.userData.alpha;p.material.uniforms.uScatter.value=p.userData.scatter;});scene.updateMatrixWorld();hotspots.forEach(h=>{let p=h.actor.position.clone();p.y+=h.dy;p.project(camera);h.b.style.left=clamp((p.x*.5+.5)*innerWidth,innerWidth*.12,innerWidth*.88)+'px';h.b.style.top=clamp((-p.y*.5+.5)*innerHeight,innerHeight*.28,innerHeight*.72)+'px';h.b.style.visibility=p.z<0||p.z>1?'hidden':'visible';});renderer.render(scene,camera);}
const ray=new THREE.Raycaster();ray.params.Points.threshold=.3;let pointer=new THREE.Vector2();$('world').onpointerdown=e=>{if(paused||busy||cam)return;drag={x:e.clientX,y:e.clientY,moved:false};$('world').setPointerCapture(e.pointerId);};$('world').onpointermove=e=>{if(!drag||cam)return;let dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>3){drag.moved=true;look.x-=dx*.008;look.y=clamp(look.y+dy*.004,-.3,3.2);drag.x=e.clientX;drag.y=e.clientY;}};$('world').onpointerup=e=>{if(drag&&!drag.moved&&!cam&&!busy){pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);ray.setFromCamera(pointer,camera);let hits=ray.intersectObjects(hotspots.filter(h=>h.b.style.display!=='none'&&h.b.style.visibility!=='hidden').map(h=>h.actor),false);if(hits.length){let h=hotspots.find(h=>h.actor===hits[0].object&&h.b.style.display!=='none'&&h.b.style.visibility!=='hidden');if(h)h.fn();}}drag=null;};
$('start').onclick=()=>{initAudio();$('intro').style.display='none';st={chapter:0,ration:[0,0],path:'',boundary:'',decision:''};prologue();};$('continue').onclick=()=>{initAudio();$('intro').style.display='none';next(st.chapter);};$('sound').onclick=()=>{muted=!muted;$('sound').textContent=muted?'声音 关':'声音 开';if(bus)gainTo(bus.gain,muted?0:.65,.15);if(musicOut)gainTo(musicOut.gain,muted?0:musicTarget,.3);};$('fullscreen').onclick=()=>document.fullscreenElement?document.exitFullscreen?.():document.documentElement.requestFullscreen?.();function pause(on){paused=on;$('pause').style.display=on?'flex':'none';if(on){ac?.suspend();tracks.forEach(a=>a.pause());sfxActive.forEach(a=>a.pause());}else{ac?.resume();if(current>=0)tracks[current].play().catch(()=>{});sfxActive.forEach(a=>a.play().catch(()=>{}));}}$('pauseButton').onclick=()=>pause(true);$('resume').onclick=()=>pause(false);$('restart').onclick=()=>{pause(false);st={chapter:0,ration:[0,0],path:'',boundary:'',decision:''};prologue();};$('credits').onclick=showSources;document.onkeydown=e=>{if(e.key==='Escape')pause(!paused);};
function audioRMS(){if(!audioMeter)return 0;let a=new Float32Array(audioMeter.fftSize);audioMeter.getFloatTimeDomainData(a);let sum=0;for(let x of a)sum+=x*x;return Math.sqrt(sum/a.length);}
window.Game={captureStream:()=>{let stream=$('world').captureStream(30);if(recordDest)recordDest.stream.getAudioTracks().forEach(t=>stream.addTrack(t));return stream;},getState:()=>({...st,chapter,mode,busy,camMoving:!!cam,grain:{ticket:grain.ticket,cash:grain.cash,queue:grain.queue,phase:grain.phase,amount:grain.amount,meal:grain.meal}}),getAudioStatus:()=>({current,title:scoreTitles[current],musicTarget,muted,rms:audioRMS(),tracks:tracks.map(a=>({ready:a.readyState,error:a.error?.message||null,paused:a.paused}))}),renderer,scene,camera};document.fonts.ready.then(()=>{let a=form('person',-4,1,-2,5,GOLD,10000),b=form('person',4,1,-2,5,BLUE,10000);a.userData.alpha=b.userData.alpha=.4;requestAnimationFrame(loop);});
})();
